import type { Metadata } from "next";
//import { Inter } from "next/font/google";
import { IBM_Plex_Sans} from 'next/font/google'
import "./globals.css";
import { NotificationsProvider} from '@/context/NotificationsContext'

//const inter = Inter({ subsets: ["latin"] });
const ibm_plex_sans = IBM_Plex_Sans({ subsets: ['latin'], weight: ['400','500', '600', '700'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ibm_plex_sans.className}>
        <NotificationsProvider>
        {children}
        </NotificationsProvider>
      </body>
    </html>
  );
}
